// <auto-generated />
using System;
using LeagueOfLegends.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeagueOfLegends.Database.Migrations
{
    [DbContext(typeof(LeagueOfLegendsDbContext))]
    [Migration("20260923141649_TeamGovernance")]
    partial class TeamGovernance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Champions", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.GamePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdModerator")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdModerator");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdStatus");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("IdTeam", "IdStatus", "CreationDate");

                    b.ToTable("GamePosts", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.GamePostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GamePostStatuses", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Lane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Lanes", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.LfgAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdLane")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegion")
                        .HasColumnType("int");

                    b.Property<int?>("IdTeam")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdLane");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdRegion");

                    b.HasIndex("IdTeam");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("IsActive", "ExpiresAt", "Kind", "CreationDate");

                    b.ToTable("LfgAds", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlatformUserSnapshot", b =>
                {
                    b.Property<Guid>("PlatformUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PlatformUserPublicId");

                    b.ToTable("PlatformUserSnapshot", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FlexDivision")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("FlexLp")
                        .HasColumnType("int");

                    b.Property<string>("FlexTier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GameName")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("IdKeycloak")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdPrimaryLane")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegion")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("PlatformUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PresentationIg")
                        .HasColumnType("text");

                    b.Property<string>("PresentationIrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("SoloDivision")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("SoloLp")
                        .HasColumnType("int");

                    b.Property<string>("SoloTier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TagLine")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IdKeycloak")
                        .IsUnique()
                        .HasFilter("[IdKeycloak] IS NOT NULL");

                    b.HasIndex("IdPrimaryLane");

                    b.HasIndex("IdRegion");

                    b.HasIndex("PlatformUserPublicId")
                        .IsUnique()
                        .HasFilter("[PlatformUserPublicId] IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("GameName", "TagLine", "IdRegion")
                        .IsUnique()
                        .HasFilter("[GameName] IS NOT NULL AND [TagLine] IS NOT NULL AND [IdRegion] IS NOT NULL");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdChampion")
                        .HasColumnType("int");

                    b.Property<int>("IdKind")
                        .HasColumnType("int");

                    b.Property<int?>("IdLane")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdChampion");

                    b.HasIndex("IdKind");

                    b.HasIndex("IdLane");

                    b.HasIndex("IdPlayer", "IdChampion")
                        .IsUnique();

                    b.ToTable("PlayerChampions", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampionKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PlayerChampionKinds", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerLane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdLane")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdLane");

                    b.HasIndex("IdPlayer", "IdLane")
                        .IsUnique();

                    b.ToTable("PlayerLanes", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Share")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerPictures", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Share")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerStreams", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Share")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerVideos", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCaptain")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegion")
                        .HasColumnType("int");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Sentence")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<string>("Tag")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaptain");

                    b.HasIndex("IdRegion");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Entitled", "Discriminator")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdLane")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int?>("IdReviewer")
                        .HasColumnType("int");

                    b.Property<int>("IdSoughtRank")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdLane");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdReviewer");

                    b.HasIndex("IdSoughtRank");

                    b.HasIndex("IdStatus");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("IdTeam", "IdPlayer", "IdStatus");

                    b.ToTable("TeamApplications", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamApplicationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TeamApplicationStatuses", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdTeam");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("TeamLinks", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<int>("IdTeamRank")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdTeamRank");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("IdTeam", "IdPlayer")
                        .IsUnique();

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TeamRanks", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.GamePost", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdModeratorNavigation")
                        .WithMany()
                        .HasForeignKey("IdModerator")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany()
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.GamePostStatus", "IdStatusNavigation")
                        .WithMany("GamePosts")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Team", "IdTeamNavigation")
                        .WithMany("GamePosts")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdModeratorNavigation");

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("IdTeamNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.LfgAd", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdLaneNavigation")
                        .WithMany("LfgAds")
                        .HasForeignKey("IdLane")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("LfgAds")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Region", "IdRegionNavigation")
                        .WithMany("LfgAds")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Team", "IdTeamNavigation")
                        .WithMany("LfgAds")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdLaneNavigation");

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdRegionNavigation");

                    b.Navigation("IdTeamNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Player", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdPrimaryLaneNavigation")
                        .WithMany("PrimaryPlayers")
                        .HasForeignKey("IdPrimaryLane")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Region", "IdRegionNavigation")
                        .WithMany("Players")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdPrimaryLaneNavigation");

                    b.Navigation("IdRegionNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampion", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Champion", "IdChampionNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdChampion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.PlayerChampionKind", "IdKindNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdKind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdLaneNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdLane")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdChampionNavigation");

                    b.Navigation("IdKindNavigation");

                    b.Navigation("IdLaneNavigation");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerLane", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdLaneNavigation")
                        .WithMany("PlayerLanes")
                        .HasForeignKey("IdLane")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerLanes")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLaneNavigation");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerPicture", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerPictures")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerStream", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerStreams")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerVideo", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerVideos")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Team", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdCaptainNavigation")
                        .WithMany("CaptainedTeams")
                        .HasForeignKey("IdCaptain")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Region", "IdRegionNavigation")
                        .WithMany("Teams")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdCaptainNavigation");

                    b.Navigation("IdRegionNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamApplication", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdLaneNavigation")
                        .WithMany("TeamApplications")
                        .HasForeignKey("IdLane")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("TeamApplications")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdReviewerNavigation")
                        .WithMany()
                        .HasForeignKey("IdReviewer")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.TeamRank", "IdSoughtRankNavigation")
                        .WithMany("TeamApplications")
                        .HasForeignKey("IdSoughtRank")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.TeamApplicationStatus", "IdStatusNavigation")
                        .WithMany("TeamApplications")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Team", "IdTeamNavigation")
                        .WithMany("TeamApplications")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLaneNavigation");

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdReviewerNavigation");

                    b.Navigation("IdSoughtRankNavigation");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("IdTeamNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamLink", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Team", "IdTeamNavigation")
                        .WithMany("TeamLinks")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdTeamNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamMember", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("TeamMembers")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Team", "IdTeamNavigation")
                        .WithMany("TeamMembers")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.TeamRank", "IdTeamRankNavigation")
                        .WithMany("TeamMembers")
                        .HasForeignKey("IdTeamRank")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdTeamNavigation");

                    b.Navigation("IdTeamRankNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Champion", b =>
                {
                    b.Navigation("PlayerChampions");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.GamePostStatus", b =>
                {
                    b.Navigation("GamePosts");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Lane", b =>
                {
                    b.Navigation("LfgAds");

                    b.Navigation("PlayerChampions");

                    b.Navigation("PlayerLanes");

                    b.Navigation("PrimaryPlayers");

                    b.Navigation("TeamApplications");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Player", b =>
                {
                    b.Navigation("CaptainedTeams");

                    b.Navigation("LfgAds");

                    b.Navigation("PlayerChampions");

                    b.Navigation("PlayerLanes");

                    b.Navigation("PlayerPictures");

                    b.Navigation("PlayerStreams");

                    b.Navigation("PlayerVideos");

                    b.Navigation("TeamApplications");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampionKind", b =>
                {
                    b.Navigation("PlayerChampions");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Region", b =>
                {
                    b.Navigation("LfgAds");

                    b.Navigation("Players");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Team", b =>
                {
                    b.Navigation("GamePosts");

                    b.Navigation("LfgAds");

                    b.Navigation("TeamApplications");

                    b.Navigation("TeamLinks");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamApplicationStatus", b =>
                {
                    b.Navigation("TeamApplications");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.TeamRank", b =>
                {
                    b.Navigation("TeamApplications");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
