// <auto-generated />
using System;
using LeagueOfLegends.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeagueOfLegends.Database.Migrations
{
    [DbContext(typeof(LeagueOfLegendsDbContext))]
    [Migration("20260923115639_PlayerRiotIdentity")]
    partial class PlayerRiotIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Champions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "aatrox",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Aatrox",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "ahri",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Ahri",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "akali",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Akali",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Code = "alistar",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Alistar",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Code = "amumu",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Amumu",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Code = "anivia",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Anivia",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Code = "annie",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Annie",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Code = "aphelios",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Aphelios",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Code = "ashe",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Ashe",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Code = "azir",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Azir",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Code = "bard",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Bard",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Code = "blitzcrank",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Blitzcrank",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Code = "brand",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Brand",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Code = "braum",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Braum",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Code = "caitlyn",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Caitlyn",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Code = "camille",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Camille",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Code = "cassiopeia",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Cassiopeia",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Code = "darius",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Darius",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Code = "diana",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Diana",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Code = "draven",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Draven",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Code = "ekko",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Ekko",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Code = "evelynn",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Evelynn",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Code = "ezreal",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Ezreal",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Code = "fiora",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Fiora",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Code = "fizz",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Fizz",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Code = "gnar",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Gnar",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Code = "graves",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Graves",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Code = "hecarim",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Hecarim",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Code = "illaoi",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Illaoi",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Code = "irelia",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Irelia",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            Code = "janna",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Janna",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            Code = "jarvaniv",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Jarvan IV",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            Code = "jax",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Jax",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            Code = "jhin",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Jhin",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            Code = "jinx",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Jinx",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            Code = "kaisa",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Kai'Sa",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            Code = "karma",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Karma",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            Code = "kassadin",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Kassadin",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            Code = "katarina",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Katarina",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            Code = "kayle",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Kayle",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            Code = "kayn",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Kayn",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            Code = "khazix",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Kha'Zix",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            Code = "kindred",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Kindred",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            Code = "leblanc",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "LeBlanc",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            Code = "leesin",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Lee Sin",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            Code = "leona",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Leona",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            Code = "lulu",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Lulu",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            Code = "lux",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Lux",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            Code = "malphite",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Malphite",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            Code = "missfortune",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Miss Fortune",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            Code = "mordekaiser",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Mordekaiser",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            Code = "morgana",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Morgana",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            Code = "nami",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Nami",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            Code = "nasus",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Nasus",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            Code = "nautilus",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Nautilus",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 56,
                            Code = "nidalee",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Nidalee",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 57,
                            Code = "orianna",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Orianna",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 58,
                            Code = "ornn",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Ornn",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 59,
                            Code = "pyke",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Pyke",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 60,
                            Code = "rakan",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Rakan",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 61,
                            Code = "renekton",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Renekton",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 62,
                            Code = "riven",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Riven",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 63,
                            Code = "senna",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Senna",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 64,
                            Code = "seraphine",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Seraphine",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 65,
                            Code = "sett",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Sett",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 66,
                            Code = "sion",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Sion",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 67,
                            Code = "sivir",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Sivir",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 68,
                            Code = "sona",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Sona",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 69,
                            Code = "soraka",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Soraka",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 70,
                            Code = "syndra",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Syndra",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 71,
                            Code = "thresh",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Thresh",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 72,
                            Code = "tristana",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Tristana",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 73,
                            Code = "twitch",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Twitch",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 74,
                            Code = "varus",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Varus",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 75,
                            Code = "vayne",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Vayne",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 76,
                            Code = "veigar",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Veigar",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 77,
                            Code = "viego",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Viego",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 78,
                            Code = "viktor",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Viktor",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 79,
                            Code = "warwick",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Warwick",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 80,
                            Code = "xayah",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Xayah",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 81,
                            Code = "xinzhao",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Xin Zhao",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 82,
                            Code = "yasuo",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Yasuo",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 83,
                            Code = "yone",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Yone",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 84,
                            Code = "yuumi",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Yuumi",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 85,
                            Code = "zed",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Zed",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 86,
                            Code = "zeri",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Zeri",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 87,
                            Code = "zoe",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Zoe",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 88,
                            Code = "zyra",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Zyra",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Lane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Lanes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "top",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Top",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "jungle",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Jungle",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "mid",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Mid",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "bottom",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Bottom",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "support",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Support",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlatformUserSnapshot", b =>
                {
                    b.Property<Guid>("PlatformUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PlatformUserPublicId");

                    b.ToTable("PlatformUserSnapshot", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FlexDivision")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("FlexLp")
                        .HasColumnType("int");

                    b.Property<string>("FlexTier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GameName")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("IdKeycloak")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdPrimaryLane")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegion")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("PlatformUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PresentationIg")
                        .HasColumnType("text");

                    b.Property<string>("PresentationIrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("SoloDivision")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("SoloLp")
                        .HasColumnType("int");

                    b.Property<string>("SoloTier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TagLine")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IdKeycloak")
                        .IsUnique()
                        .HasFilter("[IdKeycloak] IS NOT NULL");

                    b.HasIndex("IdPrimaryLane");

                    b.HasIndex("IdRegion");

                    b.HasIndex("PlatformUserPublicId")
                        .IsUnique()
                        .HasFilter("[PlatformUserPublicId] IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("GameName", "TagLine", "IdRegion")
                        .IsUnique()
                        .HasFilter("[GameName] IS NOT NULL AND [TagLine] IS NOT NULL AND [IdRegion] IS NOT NULL");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdChampion")
                        .HasColumnType("int");

                    b.Property<int>("IdKind")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdChampion");

                    b.HasIndex("IdKind");

                    b.HasIndex("IdPlayer", "IdChampion")
                        .IsUnique();

                    b.ToTable("PlayerChampions", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampionKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PlayerChampionKinds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "main",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Main",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "pool",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Pool",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "learning",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Learning",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerLane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdLane")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdLane");

                    b.HasIndex("IdPlayer", "IdLane")
                        .IsUnique();

                    b.ToTable("PlayerLanes", (string)null);
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "euw",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "EU West",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "eune",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "EU Nordic & East",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "na",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "North America",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "kr",
                            CreationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Entitled = "Korea",
                            ModificationDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Player", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdPrimaryLaneNavigation")
                        .WithMany("PrimaryPlayers")
                        .HasForeignKey("IdPrimaryLane")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueOfLegends.Database.Models.Region", "IdRegionNavigation")
                        .WithMany("Players")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdPrimaryLaneNavigation");

                    b.Navigation("IdRegionNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampion", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Champion", "IdChampionNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdChampion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.PlayerChampionKind", "IdKindNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdKind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerChampions")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdChampionNavigation");

                    b.Navigation("IdKindNavigation");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerLane", b =>
                {
                    b.HasOne("LeagueOfLegends.Database.Models.Lane", "IdLaneNavigation")
                        .WithMany("PlayerLanes")
                        .HasForeignKey("IdLane")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueOfLegends.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerLanes")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLaneNavigation");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Champion", b =>
                {
                    b.Navigation("PlayerChampions");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Lane", b =>
                {
                    b.Navigation("PlayerLanes");

                    b.Navigation("PrimaryPlayers");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Player", b =>
                {
                    b.Navigation("PlayerChampions");

                    b.Navigation("PlayerLanes");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.PlayerChampionKind", b =>
                {
                    b.Navigation("PlayerChampions");
                });

            modelBuilder.Entity("LeagueOfLegends.Database.Models.Region", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
